apiVersion: v1
kind: Service
metadata:
  name: todoapp-app
  labels:
    app: todoapp-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: todoapp-app